---
title: "DataCamp Presentation Notes"
output: html_notebook
---

### Purpose of Research project slide

It is no suprise that technology plays a huge role in statistics and education. Even introductory courses 
are utilizing statistical software like R.

Non-statistics major students (like those in STAT 217) have a lot of trouble with R because they've never seen anything like it.

In my first statistics class at cal poly (STAT 150) we were intoduced to R and I remember feeling very intimidated.

I was happy to be chosen for this project because I understand student difficulties and wanted to help make the transition to coding easier for them.

The stat 217 class has a lab assignment every week that requires students to use R.
Dr. Pileggi's old pre-lab materials consisted of a lab manual and video tutorial demonstrating the R commands that would be used in the lab assignment. 
To prepare for the R coding in the lab, students would review these materials then take a short quiz.

The tutorials covered all bases but watching videos is a passive activity so students would still have trouble on the lab assignments.

And that is where I come in. My job this summer was to convert the old (passive) pre-lab activities to an interactive R programming course on a website called DataCamp. So instead of watching the tutorials, students will actively practive coding in R to prepare them for the lab assignments.


### What is DataCamp

I created the course on DataCamp, which is a website that provides online courses in programming languages, including R.

DataCamp is similar to swirl in a few ways: 

Its an interactive teaching tool. When students submit their code and recieve instant feedback; if they get something wrong, different error messages will come up depending on what needs to be fixed. 

It is also open source so educators can create their own lessons that coincide with their university course.

A big difference between swirl is that DataCamp is a web-based application so students don't need to install anything on their personal computers.

As long as you are a college professor you can create an academic group and all of the courses are free for students.

Also its really easy to track student progress because the datacamp course can be linked with LMS. So the course I created for Dr. Pileggi's STAT 217 class is linked to polylearn.
### Creating DataCamp course slide

###### Step 1: Review

The first step of the project was to work through all of the existing lab assignments, this includes reading lab manuals, 
watching videos, taking quiz's and completing the actual lab assignment. I took notes on the statistical concepts, syntax, and data types so that my online course would kind of mirror the previous lab content. This was a really cool part of the project because I was able to find other data sets for the DataCamp course that I thought were interesting and would be interesting for students.

###### Step 2: Practice

* Completed a few existing courses on DataCamp so I would get a better understanding of how the courses were set up.

###### Step 3: Create 

* Then I read through all of the DataCamp documentation on creating a course.
* And finally I started the building process. This proved to be a huge learning curve; given that the DataCamp course is interactive, I spent
a lot of time predicting what students would get wrong then writing the corresponding error messages.

### Demonstration Slide

* For the sct's, this is the code that would compare the students answer to the solution so that the appropriate feedback would come up.

* Use Lab 5 exercise 2
  + Say that this is from Lab 5 which is all about one sample t-tests and the exercise is teaching the R code needed to check assumtions of the test.
  + Explain the parts of the page that I wrote and how that translated to what students see
  + Run the code only with the library command --> show the error message
  + Don't use correct syntax for favstats --> show error message
  + Click the get hint button then the show response button and submit
  + Read the success message outloud (this needs to be rewritten to include more info on assumptions)


### Tools
##### Learning
Used polylearn to re-learn introductory statistics material and I used the documentation on DataCamp to help build the course. 

##### Building
For creating the course, I used GitHub which is a version control utility and every datacamp course is linked through GitHub so I was able to get some experience working with version control.

And I obviously used DataCamp - I mostly wrote the STAT 217 course on the DataCamp editing page.

##### Journal Article

This project has also led to an article that I am co-authoring for a statistics education journal. In the article we are introducing DataCamp as a new technology that other educators can ulilize for their own courses. 

For this paper I use a reference management software called Mendeley which has helped with the citing references and writing the bibliography.

I'm also using LaTeX to write the article; LaTeX is a programming language used for typesetting documents. This summer was the first time I've used it but I really like it and this slideshow is actually written in LaTeX.

### Acknowledgement

And lastly, I'd like to thank Bill and Linda Frost for giving me this opportunity to take part in undergraduate research. It was an amazing experience.


