---
title: "Outline"
author: "Shannon Pileggi"
date: "July 21, 2017"
output: html_document
---

### Target Journal: 
[*Technology Innovations in Statistics Education*](http://escholarship.org/uc/uclastat_cts_tise)

### Authors (in no particular order)
+ Shannon Pileggi (mailto:spileggi@calpoly.edu), Assistant Professor, Statistics Department, Cal Poly SLO
+ Tessa Mcdonnel (mailto:tessamcdonnel@ymail.com), Undergraduate Research Assistant, Statistics Department, Cal Poly SLO
+ Weston Stearns??? (mailto:weston@datacamp.com), Lead Community Course Development, DataCamp
+ Mine Cetinkaya-Rundel??? (mailto:mine@stat.duke.edu) Assistant Professor?, Statistics Department, Duke

### Scope:
(3) Technology Innovations - discussions of new technology created by the author(s) 

 > New technologies should solve educational problems, provide infrastructure to assist statistics educators, or provide infrastructure to assist developers of statistics education technology. New Technology manuscripts should provide (at a minimum) a pedagogical context for the technology that includes a discussion of how the technology is meant to be used, who the intended users are, and what skills or concepts it is meant to help students learn. Manuscripts should provide a high-level description of the technology that includes discussing features of the design. Manuscripts must include a comparison and contrast with competing technologies, as appropriate. Authors should explain why the technology is innovative. Examples of New Technologies might include, but certainly not be limited to, web-based statistical software, applets designed to teach statistical concepts, or technology that harvests data for classroom use.
 
### Educational problem solved
+ Interactive platform to learn coding, with built in assistance and checks for understanding
+ User-friendly interface, unlike Swirl's interface which can be daunting for students who have never seen R
 
### Infrastructure provided to assist statistics educators
+ Take advantage of existing courses or build your own community course
+ Tutorials on how to build courses
+ Use the template course files from 'Create a DataCamp Course' dialog
+ Links to some github repositories: most importantly 'datacamp/testwhat' to help with submission correctness tests

 
### Pedagogical context
+ How technology is meant to be used - can be used as traditional homework assignment, in the classroom during lab periods, as pre-class assignments for flipped classrooms, even as a  test or assessment tools??
+ Intendend users - novice through advanced programming students will benefit, any college educator can access or contribute
+ Skills or concepts learned - focus is on coding in R to obtain statistical results, with some interpretation

### High level description of technology / How to Create a DataCamp Community Course
+ What is needed to get started:  DataCamp account (verified instructor), GitHub
+ How to start building (including with collaborators)
+ Examples of DataCamp code for building different types of modules

### Comparison and contrast with competing technologies  
+ Swirl lessons
+ 'Try R' by Code School--> interactive platform but not reproducible
+ Anything else?


### Explain why technology is innovative
+ Coding lesson and instructions are juxtaposed with practice window, built in points and assessments to check for understanding, can integrate class with learning management systems
+ All DataCamp courses are linked through GitHub version control, making it easy for statistics educators to collaborate and reproduce code.

